version: '2.26'

services:
  app:
    build:
      context: .
    container_name: dreamgarden-ui
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - '.:/app'
      - /app/node_modules
      - /app/.next